# Generated by Django 5.2.17 on 2026-09-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_campaigns", "0032_session_epoch_and_instant_guards"),
        ("stewardship_jobs", "0002_taskrun_guards"),
        ("stewardship_reports", "0002_fact_guards"),
        ("stewardship_source", "0007_compaction_evidence_guard"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="campaignfactrebuilddemand",
            name="fact_demand_claim_shape",
        ),
        migrations.AddField(
            model_name="campaignfactrebuilddemand",
            name="claimed_task_fence",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaignfactrebuilddemand",
            name="claimed_worker_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="campaignfactrebuilddemand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("claimed_generation__isnull", True),
                        ("claimed_task__isnull", True),
                        ("claimed_task_fence__isnull", True),
                        ("claimed_worker_id__isnull", True),
                    ),
                    models.Q(
                        ("claimed_generation__isnull", False),
                        ("claimed_revision__gt", 0),
                        ("claimed_task__isnull", False),
                        ("claimed_task_fence__gt", 0),
                        ("claimed_task_fence__isnull", False),
                        ("claimed_worker_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fact_demand_claim_shape",
            ),
        ),
    ]
