# Generated by Django 5.2.17 on 2026-09-11 15:11

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_jobs", "0002_taskrun_guards"),
        ("stewardship_reports", "0004_demand_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="FactCompactionRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("campaign_id", models.UUIDField()),
                ("fact_set_id", models.UUIDField(unique=True)),
                ("population_scope", models.CharField(max_length=12)),
                ("source_generation", models.PositiveBigIntegerField()),
                ("submission_watermark", models.PositiveBigIntegerField()),
                ("timezone_configuration_id", models.UUIDField()),
                ("through_date", models.DateField()),
                ("row_count", models.PositiveIntegerField()),
                ("task_fence", models.PositiveBigIntegerField()),
                ("worker_id", models.UUIDField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_jobs.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_fact_compaction",
            },
        ),
    ]
