# Generated by Django 5.2.17 on 2026-09-11 17:31

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0037_sealed_intake_admission"),
        ("stewardship_campaigns", "0032_session_epoch_and_instant_guards"),
        ("stewardship_jobs", "0004_task_phase_guards"),
        ("stewardship_source", "0007_compaction_evidence_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceRefreshRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("organization_id", models.PositiveBigIntegerField()),
                ("kind", models.CharField(max_length=8)),
                ("window_canonical", models.TextField()),
                ("window_digest", models.CharField(max_length=64)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_campaigns.campaign",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
                (
                    "task_root",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_jobs.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_source_refresh_request",
            },
        ),
        migrations.CreateModel(
            name="SourceRefreshCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("kind", models.CharField(max_length=8)),
                ("cause", models.CharField(max_length=16)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commands",
                        to="stewardship_source.sourcerefreshrequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_source_refresh_command",
            },
        ),
        migrations.AddIndex(
            model_name="sourcerefreshrequest",
            index=models.Index(
                fields=["window_digest", "kind"], name="source_refresh_pending_scope"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("organization_id__gt", 0), ("organization_id__lte", 2147483647)
                ),
                name="source_refresh_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("full", "delta"))),
                name="source_refresh_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_digest__regex", "^[0-9a-f]{64}$")),
                name="source_refresh_window_digest",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("full", "delta"))),
                name="source_refresh_command_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cause__in", ("manual", "nightly", "initial", "delta", "fallback"))
                ),
                name="source_refresh_command_cause",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cause", "delta"), ("kind", "delta")),
                    models.Q(
                        models.Q(("cause", "delta"), _negated=True), ("kind", "full")
                    ),
                    _connector="OR",
                ),
                name="source_refresh_command_cause_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcerefreshcommand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cause", "manual"), _negated=True),
                    ("actor_id__isnull", False),
                    _connector="OR",
                ),
                name="source_refresh_manual_actor",
            ),
        ),
    ]
