# Generated by Django 5.2.17 on 2026-09-11 18:58

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0037_sealed_intake_admission"),
        ("stewardship_jobs", "0004_task_phase_guards"),
        ("stewardship_source", "0010_source_rejection_recovery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceRefreshAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("task_fence", models.PositiveBigIntegerField()),
                ("credential_fingerprint", models.CharField(max_length=64)),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_source.sourcerefreshrequest",
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refresh_attempt",
                        to="stewardship_source.sourcesnapshot",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_jobs.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_source_refresh_attempt",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "task_fence"), name="source_attempt_claim"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("task_fence__gt", 0)),
                        name="source_attempt_fence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("credential_fingerprint__regex", "^[0-9a-f]{64}$")
                        ),
                        name="source_attempt_credential",
                    ),
                ],
            },
        ),
    ]
