# Generated by Django 5.2.17 on 2026-09-11 19:48

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_jobs", "0004_task_phase_guards"),
        ("stewardship_source", "0012_refresh_attempt_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceRefreshFallback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("task_fence", models.PositiveBigIntegerField()),
                ("reason", models.CharField(max_length=24)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_source.sourcerefreshattempt",
                    ),
                ),
                (
                    "command",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_source.sourcerefreshcommand",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="full_fallback",
                        to="stewardship_source.sourcerefreshrequest",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_jobs.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_source_refresh_fallback",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("task_fence__gt", 0)),
                        name="source_fallback_fence",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("attempt__isnull", True), ("reason", "no_base")),
                            models.Q(
                                ("attempt__isnull", False),
                                ("reason", "incomplete_delta"),
                            ),
                            _connector="OR",
                        ),
                        name="source_fallback_reason",
                    ),
                ],
            },
        ),
    ]
