# Generated by Django 5.2.17 on 2026-09-11 20:31

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0037_sealed_intake_admission"),
        ("stewardship_source", "0014_refresh_fallback_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceRefreshTick",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("due_at", parishkit.stewardship.storage.UTCDateTimeField()),
                ("timezone", models.CharField(max_length=128)),
                ("nightly_time", models.CharField(max_length=5)),
                ("slot_key", models.CharField(max_length=64, unique=True)),
                (
                    "command",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_source.sourcerefreshcommand",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_source_refresh_tick",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("slot_key__regex", "^[0-9a-f]{64}$")),
                        name="source_tick_key",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("nightly_time__regex", "^([01][0-9]|2[0-3]):[0-5][0-9]$")
                        ),
                        name="source_tick_time",
                    ),
                ],
            },
        ),
    ]
