# Generated by Django 5.2.17 on 2026-09-11 21:57

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0039_ministry_activity_guards"),
        ("stewardship_source", "0017_current_chair_projection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChairSeedEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("assignment_record_id", models.UUIDField(unique=True)),
                ("organization_id", models.PositiveBigIntegerField()),
                ("member_duid", models.PositiveBigIntegerField()),
                ("roster_keys", models.JSONField()),
                (
                    "assignment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.ministryassignment",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_source.sourcesnapshot",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_chair_seed_evidence",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("actor_id__isnull", False),
                            ("member_duid__gt", 0),
                            ("member_duid__lt", 2147483648),
                            ("organization_id__gt", 0),
                            ("organization_id__lt", 2147483648),
                        ),
                        name="chair_seed_evidence_identity",
                    )
                ],
            },
        ),
    ]
