# Generated by Django 5.2.17 on 2026-09-11 22:02

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0041_chair_seed_evidence_guards"),
        ("stewardship_jobs", "0004_task_phase_guards"),
        ("stewardship_source", "0017_current_chair_projection"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChairReconciliation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("source_fence", models.PositiveBigIntegerField(blank=True, null=True)),
                ("decisions", models.JSONField()),
                (
                    "owner_transaction",
                    models.PositiveBigIntegerField(
                        db_default=models.Func(function="txid_current"), editable=False
                    ),
                ),
                (
                    "activation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.configurationactivation",
                    ),
                ),
                (
                    "configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_source.sourcesnapshot",
                    ),
                ),
                (
                    "source_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_jobs.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_chair_reconciliation",
            },
        ),
        migrations.CreateModel(
            name="ChairAssignmentReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("assignment_record_id", models.UUIDField(db_index=True)),
                ("close_reason", models.CharField(blank=True, max_length=24)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="closed_reviews",
                        to="stewardship_accounts.chairreconciliation",
                    ),
                ),
                (
                    "latest_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="latest_reviews",
                        to="stewardship_accounts.chairreconciliation",
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opened_reviews",
                        to="stewardship_accounts.chairreconciliation",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_chair_review",
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="chairreconciliation",
            constraint=models.UniqueConstraint(
                fields=("configuration", "snapshot"), name="chair_reconciliation_input"
            ),
        ),
        migrations.AddConstraint(
            model_name="chairreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activation__isnull", False),
                        ("source_fence__isnull", True),
                        ("source_owner__isnull", True),
                    ),
                    models.Q(
                        ("activation__isnull", True),
                        ("source_fence__gt", 0),
                        ("source_fence__isnull", False),
                        ("source_owner__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chair_reconciliation_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="chairassignmentreview",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_accounts_chairassignmentreview_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="chairassignmentreview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_by__isnull", True)),
                fields=("assignment_record_id",),
                name="chair_review_open_assignment",
            ),
        ),
        migrations.AddConstraint(
            model_name="chairassignmentreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("close_reason", ""), ("closed_by__isnull", True)),
                    models.Q(
                        (
                            "close_reason__in",
                            ("relationship_returned", "assignment_removed"),
                        ),
                        ("closed_by__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="chair_review_closure",
            ),
        ),
    ]
