# Generated by Django 5.2.17 on 2026-09-12 11:43

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0045_pristine_source_bootstrap"),
        ("stewardship_jobs", "0005_scheduler_cancellation_guard"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("session_id", models.UUIDField(unique=True)),
                ("owner_id", models.UUIDField()),
                ("state", models.CharField(default="collecting", max_length=16)),
                (
                    "renewed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "expired_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                ("expiry_reason", models.CharField(default="", max_length=16)),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
                (
                    "source_task",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_jobs.taskrun",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_setup_attempt",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_accounts_setupattempt_positive_version",
                    ),
                    models.UniqueConstraint(
                        models.Value(1),
                        condition=models.Q(
                            ("state__in", ["collecting", "loading", "frozen"])
                        ),
                        name="setup_one_pending_attempt",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "collecting",
                                    "loading",
                                    "frozen",
                                    "completed",
                                    "expired",
                                ],
                            )
                        ),
                        name="setup_known_state",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("state", "loading"), _negated=True),
                            ("source_task__isnull", False),
                            _connector="OR",
                        ),
                        name="setup_loading_task",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("expired_at__isnull", False),
                                (
                                    "expiry_reason__in",
                                    [
                                        "cancelled",
                                        "session",
                                        "idle",
                                        "watchdog",
                                        "absolute",
                                    ],
                                ),
                                ("state", "expired"),
                            ),
                            models.Q(
                                models.Q(("state", "expired"), _negated=True),
                                ("expired_at__isnull", True),
                                ("expiry_reason", ""),
                            ),
                            _connector="OR",
                        ),
                        name="setup_expiry_shape",
                    ),
                ],
            },
        ),
    ]
