# Generated by Django 5.2.17 on 2026-09-12 12:51

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0047_setup_attempt_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("record_id", models.UUIDField(db_index=True)),
                ("campaign_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=8)),
                ("slot", models.CharField(max_length=32)),
                ("subject", models.CharField(max_length=254, null=True)),
                ("html", models.TextField()),
                ("text", models.TextField()),
            ],
            options={
                "db_table": "stewardship_content_version",
            },
        ),
        migrations.RemoveConstraint(
            model_name="appliedconfigurationversion",
            name="configuration_validation_schema",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_schema",
        ),
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_actor",
        ),
        migrations.AddConstraint(
            model_name="appliedconfigurationversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "validation_schema__in",
                        [
                            "parish-integrations-v1",
                            "foundation-policy-v2",
                            "campaign-foundation-v3",
                            "bootstrap-policy-v1",
                            "ministry-activity-v4",
                            "campaign-content-v5",
                        ],
                    )
                ),
                name="configuration_validation_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "request_schema__in",
                        [
                            "parish-integrations-patch-v1",
                            "foundation-policy-patch-v2",
                            "operator-recovery-patch-v1",
                            "operator-recovery-patch-v2",
                            "operator-recovery-bootstrap-v1",
                            "campaign-foundation-patch-v3",
                            "ministry-activity-patch-v4",
                            "operator-recovery-ministry-v4",
                            "campaign-content-patch-v5",
                            "operator-recovery-content-v5",
                        ],
                    )
                ),
                name="config_request_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("actor_id__isnull", False),
                        ("authority", "admin"),
                        ("confirmed_deployment_id__isnull", True),
                        ("operator_name__isnull", True),
                        ("operator_reason__isnull", True),
                        ("recovery_target__isnull", True),
                        models.Q(
                            (
                                "request_schema__in",
                                [
                                    "operator-recovery-patch-v1",
                                    "operator-recovery-patch-v2",
                                    "operator-recovery-bootstrap-v1",
                                    "operator-recovery-ministry-v4",
                                    "operator-recovery-content-v5",
                                ],
                            ),
                            _negated=True,
                        ),
                    ),
                    models.Q(
                        ("actor_id__isnull", True),
                        ("authority", "operator_recovery"),
                        ("confirmed_deployment_id__isnull", False),
                        ("operator_name__isnull", False),
                        ("operator_reason__isnull", False),
                        ("recovery_target__isnull", False),
                        (
                            "request_schema__in",
                            [
                                "operator-recovery-patch-v1",
                                "operator-recovery-patch-v2",
                                "operator-recovery-bootstrap-v1",
                                "operator-recovery-ministry-v4",
                                "operator-recovery-content-v5",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="config_request_actor",
            ),
        ),
        migrations.AddField(
            model_name="contentversion",
            name="configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="content_versions",
                to="stewardship_accounts.appliedconfigurationversion",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.UniqueConstraint(
                fields=("configuration", "record_id"),
                name="content_revision_projection",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.UniqueConstraint(
                fields=("configuration", "campaign_id", "kind", "slot"),
                condition=models.Q(kind="page"),
                name="content_selected_slot",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "page"), ("subject__isnull", True)),
                    models.Q(
                        ("kind", "email"),
                        ("subject__isnull", False),
                        models.Q(("subject", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="content_subject_kind",
            ),
        ),
    ]
