# Generated by Django 5.2.17 on 2026-09-12 14:15

import uuid

import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0049_content_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicCredentialHandoff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("target", models.CharField(max_length=32, unique=True)),
                ("key_id", models.CharField(max_length=48)),
                ("public_key", models.BinaryField(max_length=32, unique=True)),
            ],
            options={
                "db_table": "stewardship_public_credential_handoff",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "target__in",
                                (
                                    "django_signing",
                                    "general_encryption",
                                    "family_code_mac",
                                    "token_public",
                                    "token_private",
                                    "google_oauth",
                                    "google_workspace",
                                    "parishsoft",
                                    "slack",
                                    "backup_target",
                                    "backup_data",
                                    "metrics",
                                ),
                            )
                        ),
                        name="handoff_public_known_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("key_id__regex", "^[A-Za-z0-9_-]{1,48}$")),
                        name="handoff_public_key_label",
                    ),
                ],
            },
        ),
    ]
