# Generated by Django 5.2.17 on 2026-09-12 14:42

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0051_handoff_public_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderValidationContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("target", models.CharField(max_length=32)),
                ("settings", models.JSONField()),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.secretreplacementrequest",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_provider_context",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("target__in", ["parishsoft", "google_workspace", "slack"])
                        ),
                        name="provider_context_known_target",
                    )
                ],
            },
        ),
    ]
