# Generated by Django 5.2.17 on 2026-09-12 15:09

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0053_provider_context_guards"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandingBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("owner_id", models.UUIDField()),
                ("session_id", models.UUIDField()),
                ("setup_attempt_id", models.UUIDField(null=True)),
                ("expires_at", parishkit.stewardship.storage.UTCDateTimeField()),
                (
                    "state",
                    models.CharField(
                        db_default="writing", default="writing", max_length=16
                    ),
                ),
                (
                    "base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.appliedconfigurationversion",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_branding_bundle",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BrandingAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                ("label", models.CharField(max_length=8)),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                (
                    "bundle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="stewardship_accounts.brandingbundle",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_branding_asset",
            },
        ),
        migrations.AddConstraint(
            model_name="brandingbundle",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)),
                name="stewardship_accounts_brandingbundle_positive_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingbundle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["writing", "ready", "cleanup_pending", "scrubbed"])
                ),
                name="branding_bundle_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingbundle",
            constraint=models.CheckConstraint(
                condition=models.Q(("expires_at__gt", models.F("created_at"))),
                name="branding_bundle_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingasset",
            constraint=models.UniqueConstraint(
                fields=("bundle", "label"), name="branding_asset_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("label__in", ["large", "menu", "icon", "favicon"])),
                name="branding_asset_label",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("height__gte", 1),
                    ("height__lte", 1024),
                    ("size__gte", 1),
                    ("size__lte", 5242880),
                    ("width__gte", 1),
                    ("width__lte", 1024),
                ),
                name="branding_asset_bounds",
            ),
        ),
        migrations.AddConstraint(
            model_name="brandingasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("sha256__regex", "^[0-9a-f]{64}$")),
                name="branding_asset_digest",
            ),
        ),
    ]
