# Generated by Django 5.2.17 on 2026-09-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0056_configuration_credential_receipts"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="configurationchangerequest",
            name="config_request_schema",
        ),
        migrations.AddConstraint(
            model_name="configurationchangerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "request_schema__in",
                        [
                            "parish-integrations-patch-v1",
                            "foundation-policy-patch-v2",
                            "operator-recovery-patch-v1",
                            "operator-recovery-patch-v2",
                            "operator-recovery-bootstrap-v1",
                            "campaign-foundation-patch-v3",
                            "ministry-activity-patch-v4",
                            "operator-recovery-ministry-v4",
                            "campaign-content-patch-v5",
                            "operator-recovery-content-v5",
                            "integration-credential-patch-v6",
                        ],
                    )
                ),
                name="config_request_schema",
            ),
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            """
            LOCK TABLE public.stewardship_config_request IN ACCESS EXCLUSIVE MODE;
            DO $$ BEGIN
                IF EXISTS (SELECT 1 FROM public.stewardship_config_request
                    WHERE request_schema='integration-credential-patch-v6') THEN
                    RAISE EXCEPTION 'Credential selection history prevents downgrade'
                        USING ERRCODE='23514';
                END IF;
            END $$;
            """,
        ),
    ]
