# Generated by Django 5.2.17 on 2026-09-12 16:28

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_accounts", "0058_scheduler_setup_expiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetupDraftSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "correlation_id",
                    models.UUIDField(
                        db_index=True,
                        default=parishkit.stewardship.observability.current_correlation,
                        editable=False,
                    ),
                ),
                (
                    "updated_at",
                    parishkit.stewardship.storage.UTCDateTimeField(
                        db_default=django.db.models.functions.datetime.Now(),
                        editable=False,
                    ),
                ),
                ("version", models.PositiveBigIntegerField(default=1, editable=False)),
                ("step", models.CharField(max_length=24)),
                ("values", models.JSONField()),
                (
                    "scrubbed_at",
                    parishkit.stewardship.storage.UTCDateTimeField(null=True),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="stewardship_accounts.setupattempt",
                    ),
                ),
            ],
            options={
                "db_table": "stewardship_setup_draft_section",
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_accounts_setupdraftsection_positive_version",
                    ),
                    models.UniqueConstraint(
                        fields=("attempt", "step"), name="setup_one_draft_per_step"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "step__in",
                                [
                                    "parish",
                                    "branding",
                                    "access",
                                    "mail",
                                    "slack",
                                    "testing",
                                ],
                            )
                        ),
                        name="setup_public_step",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scrubbed_at__isnull", True),
                            ("values", {}),
                            _connector="OR",
                        ),
                        name="setup_scrubbed_values_empty",
                    ),
                ],
            },
        ),
    ]
