# Generated by Django 5.2.17 on 2026-09-13 10:52

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stewardship_accounts", "0001_initial_schema"),
        ("stewardship_accounts", "0002_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="AuditEvent",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("event_type", models.CharField(max_length=64)),
                        ("subject_id", models.UUIDField(blank=True, null=True)),
                        (
                            "campaign_reference",
                            models.UUIDField(blank=True, db_index=True, null=True),
                        ),
                        (
                            "ownership_scope",
                            models.CharField(db_default="deployment", max_length=16),
                        ),
                        (
                            "parish",
                            models.ForeignKey(
                                blank=True,
                                db_default=None,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="audit_events",
                                to="stewardship_accounts.parish",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_audit_event",
                    },
                ),
                migrations.CreateModel(
                    name="AuditContext",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("actor_kind", models.CharField(max_length=16)),
                        ("schema", models.CharField(max_length=16)),
                        ("context", models.JSONField(default=dict)),
                        (
                            "event",
                            models.OneToOneField(
                                on_delete=django.db.models.deletion.PROTECT,
                                to="stewardship_audit.auditevent",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_audit_context",
                    },
                ),
                migrations.CreateModel(
                    name="OperationalLog",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("level", models.CharField(max_length=8)),
                        ("event", models.CharField(max_length=64)),
                        ("schema", models.CharField(max_length=16)),
                        ("context", models.JSONField(default=dict)),
                    ],
                    options={
                        "db_table": "stewardship_operational_log",
                        "indexes": [
                            models.Index(
                                fields=["level", "created_at"],
                                name="operational_level_time",
                            )
                        ],
                        "constraints": [
                            models.CheckConstraint(
                                condition=models.Q(
                                    (
                                        "level__in",
                                        [
                                            "DEBUG",
                                            "INFO",
                                            "WARNING",
                                            "ERROR",
                                            "CRITICAL",
                                        ],
                                    )
                                ),
                                name="operational_log_level",
                            )
                        ],
                    },
                ),
                migrations.AddIndex(
                    model_name="auditevent",
                    index=models.Index(
                        fields=["event_type", "created_at"], name="audit_event_time"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="auditevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("event_type__regex", "^[a-z][a-z0-9_]{0,63}$")
                        ),
                        name="audit_event_type_identifier",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="auditevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ownership_scope", "parish"), ("parish__isnull", False)
                            ),
                            models.Q(
                                ("campaign_reference__isnull", True),
                                ("ownership_scope", "deployment"),
                                ("parish__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="audit_ownership_shape",
                    ),
                ),
            ],
        ),
    ]
