# Generated by Django 5.2.17 on 2026-09-13 10:52

import uuid

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models

import parishkit.stewardship.observability
import parishkit.stewardship.storage


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stewardship_accounts", "0001_initial_schema"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="TaskRun",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        (
                            "updated_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "version",
                            models.PositiveBigIntegerField(default=1, editable=False),
                        ),
                        ("task_type", models.CharField(max_length=64)),
                        (
                            "idempotency_key",
                            models.CharField(blank=True, max_length=80, null=True),
                        ),
                        ("retry_sequence", models.PositiveBigIntegerField(default=0)),
                        ("retry_command_id", models.UUIDField(blank=True, null=True)),
                        ("domain_request_id", models.UUIDField(blank=True, null=True)),
                        ("initiated_by_id", models.UUIDField(blank=True, null=True)),
                        (
                            "state",
                            models.CharField(
                                db_default="queued", default="queued", max_length=16
                            ),
                        ),
                        (
                            "action",
                            models.CharField(
                                db_default="created", default="created", max_length=24
                            ),
                        ),
                        (
                            "attempt",
                            models.PositiveBigIntegerField(db_default=0, default=0),
                        ),
                        (
                            "fence",
                            models.PositiveBigIntegerField(db_default=0, default=0),
                        ),
                        ("worker_id", models.UUIDField(blank=True, null=True)),
                        (
                            "heartbeat_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                blank=True, null=True
                            ),
                        ),
                        (
                            "lease_expires_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                blank=True, null=True
                            ),
                        ),
                        (
                            "not_before",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now()
                            ),
                        ),
                        (
                            "progress_current",
                            models.PositiveBigIntegerField(db_default=0, default=0),
                        ),
                        (
                            "progress_total",
                            models.PositiveBigIntegerField(db_default=0, default=0),
                        ),
                        (
                            "phase",
                            models.CharField(
                                db_default="unspecified",
                                default="unspecified",
                                max_length=32,
                            ),
                        ),
                        (
                            "parent",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="retries",
                                to="stewardship_jobs.taskrun",
                            ),
                        ),
                        (
                            "root",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="chain_runs",
                                to="stewardship_jobs.taskrun",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_task_run",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="TaskRunEvent",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        (
                            "created_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                db_default=django.db.models.functions.datetime.Now(),
                                editable=False,
                            ),
                        ),
                        (
                            "actor_id",
                            models.UUIDField(blank=True, editable=False, null=True),
                        ),
                        (
                            "correlation_id",
                            models.UUIDField(
                                db_index=True,
                                default=parishkit.stewardship.observability.current_correlation,
                                editable=False,
                            ),
                        ),
                        ("version", models.PositiveBigIntegerField()),
                        ("previous_state", models.CharField(blank=True, max_length=16)),
                        ("state", models.CharField(max_length=16)),
                        ("action", models.CharField(max_length=24)),
                        ("attempt", models.PositiveBigIntegerField()),
                        ("fence", models.PositiveBigIntegerField()),
                        ("worker_id", models.UUIDField(blank=True, null=True)),
                        (
                            "heartbeat_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                blank=True, null=True
                            ),
                        ),
                        (
                            "lease_expires_at",
                            parishkit.stewardship.storage.UTCDateTimeField(
                                blank=True, null=True
                            ),
                        ),
                        (
                            "not_before",
                            parishkit.stewardship.storage.UTCDateTimeField(),
                        ),
                        ("progress_current", models.PositiveBigIntegerField()),
                        ("progress_total", models.PositiveBigIntegerField()),
                        (
                            "phase",
                            models.CharField(
                                db_default="unspecified",
                                default="unspecified",
                                max_length=32,
                            ),
                        ),
                        (
                            "run",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="events",
                                to="stewardship_jobs.taskrun",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "stewardship_task_event",
                    },
                ),
                migrations.AddIndex(
                    model_name="taskrun",
                    index=models.Index(fields=["state", "not_before"], name="task_due"),
                ),
                migrations.AddIndex(
                    model_name="taskrun",
                    index=models.Index(
                        fields=["state", "lease_expires_at"], name="task_lease"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="stewardship_jobs_taskrun_positive_version",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("idempotency_key__isnull", False)),
                        fields=("task_type", "idempotency_key"),
                        name="task_execution_key",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.UniqueConstraint(
                        fields=("root", "retry_sequence"), name="task_retry_sequence"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                ("queued", "running", "retry_wait", "abandoned"),
                            )
                        ),
                        fields=("root",),
                        name="task_one_nonterminal",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("retry_command_id__isnull", False)),
                        fields=("root", "retry_command_id"),
                        name="task_retry_command",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                (
                                    "queued",
                                    "running",
                                    "retry_wait",
                                    "abandoned",
                                    "succeeded",
                                    "failed",
                                    "cancelled",
                                ),
                            )
                        ),
                        name="task_known_state",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "action__in",
                                (
                                    "created",
                                    "explicit_retry",
                                    "claim",
                                    "heartbeat",
                                    "progress",
                                    "complete",
                                    "retryable_failure",
                                    "permanent_failure",
                                    "safe_cancel",
                                    "lease_expired",
                                    "recovery_retry",
                                    "recovery_complete",
                                    "recovery_fail",
                                    "recovery_cancel",
                                ),
                            )
                        ),
                        name="task_known_action",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("task_type__regex", "^[a-z][a-z0-9_]{0,63}$")
                        ),
                        name="task_type_identifier",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            ("progress_current__lte", models.F("progress_total"))
                        ),
                        name="task_progress_bounds",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("fence__gte", models.F("attempt"))),
                        name="task_fence_bounds",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("heartbeat_at__isnull", False),
                                ("lease_expires_at__isnull", False),
                                ("state", "running"),
                                ("worker_id__isnull", False),
                            ),
                            models.Q(
                                models.Q(("state", "running"), _negated=True),
                                ("lease_expires_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="task_claim_shape",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrun",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "phase__in",
                                (
                                    "unspecified",
                                    "starting",
                                    "preparing",
                                    "fetching",
                                    "validating",
                                    "staging",
                                    "promoting",
                                    "reconciling",
                                    "rendering",
                                    "delivering",
                                    "verifying",
                                    "compacting",
                                    "draining",
                                    "deleting",
                                    "uploading",
                                ),
                            )
                        ),
                        name="task_phase_known",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrunevent",
                    constraint=models.UniqueConstraint(
                        fields=("run", "version"), name="task_event_version"
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrunevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="task_event_positive",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="taskrunevent",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            (
                                "phase__in",
                                (
                                    "unspecified",
                                    "starting",
                                    "preparing",
                                    "fetching",
                                    "validating",
                                    "staging",
                                    "promoting",
                                    "reconciling",
                                    "rendering",
                                    "delivering",
                                    "verifying",
                                    "compacting",
                                    "draining",
                                    "deleting",
                                    "uploading",
                                ),
                            )
                        ),
                        name="task_event_phase_known",
                    ),
                ),
            ],
        ),
    ]
