# Generated by Django 5.2.17 on 2026-09-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stewardship_jobs", "0002_taskrun_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrun",
            name="phase",
            field=models.CharField(
                db_default="unspecified", default="unspecified", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="taskrunevent",
            name="phase",
            field=models.CharField(
                db_default="unspecified", default="unspecified", max_length=32
            ),
        ),
        migrations.AddConstraint(
            model_name="taskrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "phase__in",
                        (
                            "unspecified",
                            "starting",
                            "preparing",
                            "fetching",
                            "validating",
                            "staging",
                            "promoting",
                            "reconciling",
                            "rendering",
                            "delivering",
                            "verifying",
                            "compacting",
                            "draining",
                            "deleting",
                            "uploading",
                        ),
                    )
                ),
                name="task_phase_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskrunevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "phase__in",
                        (
                            "unspecified",
                            "starting",
                            "preparing",
                            "fetching",
                            "validating",
                            "staging",
                            "promoting",
                            "reconciling",
                            "rendering",
                            "delivering",
                            "verifying",
                            "compacting",
                            "draining",
                            "deleting",
                            "uploading",
                        ),
                    )
                ),
                name="task_event_phase_known",
            ),
        ),
    ]
