# Generated by Django 5.2.17 on 2026-09-12 12:28

from django.db import migrations, models

import parishkit.stewardship.storage


class Migration(migrations.Migration):
    dependencies = [
        ("sessions", "0001_initial"),
        ("stewardship_campaigns", "0032_session_epoch_and_instant_guards"),
    ]

    operations = [
        migrations.AddField(
            model_name="familysession",
            name="presence_at",
            field=parishkit.stewardship.storage.UTCDateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="familysession",
            name="presence_section",
            field=models.CharField(blank=True, default="", max_length=24),
        ),
        migrations.AddIndex(
            model_name="familysession",
            index=models.Index(
                fields=["presence_at", "id"], name="family_session_presence"
            ),
        ),
        migrations.AddConstraint(
            model_name="familysession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("presence_at__isnull", True), ("presence_section", "")),
                    models.Q(
                        ("presence_at__gte", models.F("authenticated_at")),
                        ("presence_at__isnull", False),
                        ("presence_at__lt", models.F("expires_at")),
                        (
                            "presence_section__in",
                            (
                                "welcome",
                                "census",
                                "members",
                                "ministry",
                                "financial",
                                "additional",
                                "review",
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="family_presence_shape",
            ),
        ),
    ]
